// Copyright (c) Daniel Crenna. All rights reserved.
// 
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, you can obtain one at http://mozilla.org/MPL/2.0/.

using System.Runtime.InteropServices;
using System.Text;

namespace BetterAPI.SourceGenerators
{
    internal static class StringBuilderExtensions
    {
        public static IStringBuilder InsertAutoGeneratedHeader(this IStringBuilder sb)
        {            
            var h = new StringBuilder();
            h.AppendLine($"//------------------------------------------------------------------------------");
            h.AppendLine($"// <auto-generated>");
            h.AppendLine($"//     This code was generated by a tool.");
            h.AppendLine($"//     Runtime Version: {RuntimeInformation.FrameworkDescription}");
            h.AppendLine($"//");
            h.AppendLine($"//     Changes to this file may cause incorrect behavior and will be lost if");
            h.AppendLine($"//     the code is regenerated.");
            h.AppendLine($"// </auto-generated>");
            h.AppendLine($"//------------------------------------------------------------------------------");
            h.AppendLine();
            sb.Insert(0, h);
            return sb;
        }

        public static StringBuilder AppendLine(this StringBuilder sb, int indent, string message)
        {
            if(indent > 0)
                AppendTabSpaces(sb, indent);
            sb.AppendLine(message);
            return sb;
        }

        public static IStringBuilder AppendLine(this IStringBuilder sb, int indent, string message)
        {
            if (indent > 0)
                AppendTabSpaces(sb, indent);
            sb.AppendLine(message);
            return sb;
        }

        public static StringBuilder AppendLine(this StringBuilder sb, string message, bool condition)
        {
            if (!condition)
                return sb;            
            sb.AppendLine(message);
            return sb;
        }

        private static StringBuilder AppendTabSpaces(StringBuilder sb, int indent, int tabLength = 4)
        {
            for (var i = 0; i < indent; i++)
                sb.Append(new string(' ', tabLength));
            return sb;
        }

        private static IStringBuilder AppendTabSpaces(IStringBuilder sb, int indent, int tabLength = 4)
        {
            for (var i = 0; i < indent; i++)
                sb.Append(new string(' ', tabLength));
            return sb;
        }
    }
}